root: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
extends:
  # - eslint:recommended
  - plugin:react/recommended
env:
  es6: true
rules:
  react/prop-types: 
    - off
  no-unused-vars: off
  semi:
    - error
    - never